### ISSUE TITLE
There is no property to not send the root model name in requests

### ISSUE THREAD

**Issue by noelrocha** [dingbat/nsrails#61] opened 2014-05-31 05:08 UTC
Hi,

there is no way to avoid NSRails to insert the model name in POSTs.

How to avoid that?

**Comment by dingbat** [comment] 2014-06-01 22:41
Hi there,

I assume you mean the JSON being sent as `{"user"=>{"name"=>"x", "email"=>"y"}}` instead of `{"name"=>"x", "email"=>"y"}`, for example.

The method that JSON-izes your object, `remoteDictionaryRepresentationWrapped:` on NSRRemoteObject, takes a boolean parameter of whether or not this should happen. The issue is that NSRRequest, what forms the POST requests you're probably making, [calls this with YES.](https://github.com/dingbat/nsrails/blob/master/nsrails/Source/NSRRequest.m#L134)

So as I see it you could do two things:
1. Craft NSRRequests manually whose request bodies don't wrap the JSON, but then you'd have to do all the object update followup (which is just one line really) manually as well:
   
   ``` objc
   NSRRequest *r = [NSRRequest requestToCreateObject:obj];
   r.body = [obj remoteDictionaryRepresentationWrapped:NO];
   [r sendAsynchronous:^(id ret, NSError *err) {
      //check for error
      [obj setPropertiesUsingRemoteDictionary:ret];
   }];
   ```
   
   Of course if you're doing this often it can be refactored & the burden isn't so bad.
2. Or, you could go the more hacky way and override `remoteDictionaryRepresentationWrapped:` in your model to always return NO:
   
   ``` objc
   - (NSDictionary *) remoteDictionaryRepresentationWrapped:(BOOL)wrapped {
      return [super remoteDictionaryRepresentationWrapped:NO];
   }
   ```
   
   This is less advised, and also you'd have to make sure you _never_ want this wrapping to happen.

The other obvious alternative I suppose is to support the wrapping server-side. If you're using Rails this is a given, but of course looks like you aren't.

**Comment by dingbat** [comment] 2014-06-13 02:57
Closing, feel free to comment if you have any questions.

**Closed as completed by dingbat** 2014-06-13 02:57 UTC
